//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BitirmeTeziDatabaseModel", "FK__Research___Acd_i__00200768", "Academic", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BitirmeTeziDatabaseModel.Academic), "Research_Thesis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BitirmeTeziDatabaseModel.Research_Thesis), true)]
[assembly: EdmRelationshipAttribute("BitirmeTeziDatabaseModel", "FK__Upload_Th__Super__08B54D69", "Academic", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BitirmeTeziDatabaseModel.Academic), "Upload_Thesis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BitirmeTeziDatabaseModel.Upload_Thesis), true)]
[assembly: EdmRelationshipAttribute("BitirmeTeziDatabaseModel", "FK__Upload_Th__Std_i__07C12930", "Student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BitirmeTeziDatabaseModel.Student), "Upload_Thesis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BitirmeTeziDatabaseModel.Upload_Thesis), true)]

#endregion

namespace BitirmeTeziDatabaseModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BitirmeTeziDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BitirmeTeziDatabaseEntities object using the connection string found in the 'BitirmeTeziDatabaseEntities' section of the application configuration file.
        /// </summary>
        public BitirmeTeziDatabaseEntities() : base("name=BitirmeTeziDatabaseEntities", "BitirmeTeziDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BitirmeTeziDatabaseEntities object.
        /// </summary>
        public BitirmeTeziDatabaseEntities(string connectionString) : base(connectionString, "BitirmeTeziDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BitirmeTeziDatabaseEntities object.
        /// </summary>
        public BitirmeTeziDatabaseEntities(EntityConnection connection) : base(connection, "BitirmeTeziDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Academic> Academics
        {
            get
            {
                if ((_Academics == null))
                {
                    _Academics = base.CreateObjectSet<Academic>("Academics");
                }
                return _Academics;
            }
        }
        private ObjectSet<Academic> _Academics;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Past_Thesis> Past_Thesis
        {
            get
            {
                if ((_Past_Thesis == null))
                {
                    _Past_Thesis = base.CreateObjectSet<Past_Thesis>("Past_Thesis");
                }
                return _Past_Thesis;
            }
        }
        private ObjectSet<Past_Thesis> _Past_Thesis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Research_Thesis> Research_Thesis
        {
            get
            {
                if ((_Research_Thesis == null))
                {
                    _Research_Thesis = base.CreateObjectSet<Research_Thesis>("Research_Thesis");
                }
                return _Research_Thesis;
            }
        }
        private ObjectSet<Research_Thesis> _Research_Thesis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Student> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Student>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Student> _Students;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Upload_Thesis> Upload_Thesis
        {
            get
            {
                if ((_Upload_Thesis == null))
                {
                    _Upload_Thesis = base.CreateObjectSet<Upload_Thesis>("Upload_Thesis");
                }
                return _Upload_Thesis;
            }
        }
        private ObjectSet<Upload_Thesis> _Upload_Thesis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Academics EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAcademics(Academic academic)
        {
            base.AddObject("Academics", academic);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Past_Thesis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPast_Thesis(Past_Thesis past_Thesis)
        {
            base.AddObject("Past_Thesis", past_Thesis);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Research_Thesis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResearch_Thesis(Research_Thesis research_Thesis)
        {
            base.AddObject("Research_Thesis", research_Thesis);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Upload_Thesis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUpload_Thesis(Upload_Thesis upload_Thesis)
        {
            base.AddObject("Upload_Thesis", upload_Thesis);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitirmeTeziDatabaseModel", Name="Academic")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Academic : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Academic object.
        /// </summary>
        /// <param name="acd_id">Initial value of the Acd_id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="education">Initial value of the Education property.</param>
        /// <param name="interests">Initial value of the Interests property.</param>
        public static Academic CreateAcademic(global::System.Int32 acd_id, global::System.String username, global::System.String name, global::System.String email, global::System.String phone, global::System.String education, global::System.String interests)
        {
            Academic academic = new Academic();
            academic.Acd_id = acd_id;
            academic.Username = username;
            academic.Name = name;
            academic.Email = email;
            academic.Phone = phone;
            academic.Education = education;
            academic.Interests = interests;
            return academic;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Acd_id
        {
            get
            {
                return _Acd_id;
            }
            set
            {
                if (_Acd_id != value)
                {
                    OnAcd_idChanging(value);
                    ReportPropertyChanging("Acd_id");
                    _Acd_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Acd_id");
                    OnAcd_idChanged();
                }
            }
        }
        private global::System.Int32 _Acd_id;
        partial void OnAcd_idChanging(global::System.Int32 value);
        partial void OnAcd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Education
        {
            get
            {
                return _Education;
            }
            set
            {
                OnEducationChanging(value);
                ReportPropertyChanging("Education");
                _Education = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Education");
                OnEducationChanged();
            }
        }
        private global::System.String _Education;
        partial void OnEducationChanging(global::System.String value);
        partial void OnEducationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Interests
        {
            get
            {
                return _Interests;
            }
            set
            {
                OnInterestsChanging(value);
                ReportPropertyChanging("Interests");
                _Interests = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Interests");
                OnInterestsChanged();
            }
        }
        private global::System.String _Interests;
        partial void OnInterestsChanging(global::System.String value);
        partial void OnInterestsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BitirmeTeziDatabaseModel", "FK__Research___Acd_i__00200768", "Research_Thesis")]
        public EntityCollection<Research_Thesis> Research_Thesis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Research_Thesis>("BitirmeTeziDatabaseModel.FK__Research___Acd_i__00200768", "Research_Thesis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Research_Thesis>("BitirmeTeziDatabaseModel.FK__Research___Acd_i__00200768", "Research_Thesis", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BitirmeTeziDatabaseModel", "FK__Upload_Th__Super__08B54D69", "Upload_Thesis")]
        public EntityCollection<Upload_Thesis> Upload_Thesis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Upload_Thesis>("BitirmeTeziDatabaseModel.FK__Upload_Th__Super__08B54D69", "Upload_Thesis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Upload_Thesis>("BitirmeTeziDatabaseModel.FK__Upload_Th__Super__08B54D69", "Upload_Thesis", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitirmeTeziDatabaseModel", Name="Past_Thesis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Past_Thesis : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Past_Thesis object.
        /// </summary>
        /// <param name="thesis_id">Initial value of the Thesis_id property.</param>
        /// <param name="std_name">Initial value of the Std_name property.</param>
        /// <param name="supervisor">Initial value of the Supervisor property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="document">Initial value of the Document property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        public static Past_Thesis CreatePast_Thesis(global::System.Int32 thesis_id, global::System.String std_name, global::System.String supervisor, global::System.String title, global::System.String content, global::System.String document, global::System.Int32 year)
        {
            Past_Thesis past_Thesis = new Past_Thesis();
            past_Thesis.Thesis_id = thesis_id;
            past_Thesis.Std_name = std_name;
            past_Thesis.Supervisor = supervisor;
            past_Thesis.Title = title;
            past_Thesis.Content = content;
            past_Thesis.Document = document;
            past_Thesis.Year = year;
            return past_Thesis;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Thesis_id
        {
            get
            {
                return _Thesis_id;
            }
            set
            {
                if (_Thesis_id != value)
                {
                    OnThesis_idChanging(value);
                    ReportPropertyChanging("Thesis_id");
                    _Thesis_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Thesis_id");
                    OnThesis_idChanged();
                }
            }
        }
        private global::System.Int32 _Thesis_id;
        partial void OnThesis_idChanging(global::System.Int32 value);
        partial void OnThesis_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Std_name
        {
            get
            {
                return _Std_name;
            }
            set
            {
                OnStd_nameChanging(value);
                ReportPropertyChanging("Std_name");
                _Std_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Std_name");
                OnStd_nameChanged();
            }
        }
        private global::System.String _Std_name;
        partial void OnStd_nameChanging(global::System.String value);
        partial void OnStd_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Supervisor
        {
            get
            {
                return _Supervisor;
            }
            set
            {
                OnSupervisorChanging(value);
                ReportPropertyChanging("Supervisor");
                _Supervisor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Supervisor");
                OnSupervisorChanged();
            }
        }
        private global::System.String _Supervisor;
        partial void OnSupervisorChanging(global::System.String value);
        partial void OnSupervisorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Document
        {
            get
            {
                return _Document;
            }
            set
            {
                OnDocumentChanging(value);
                ReportPropertyChanging("Document");
                _Document = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Document");
                OnDocumentChanged();
            }
        }
        private global::System.String _Document;
        partial void OnDocumentChanging(global::System.String value);
        partial void OnDocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitirmeTeziDatabaseModel", Name="Research_Thesis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Research_Thesis : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Research_Thesis object.
        /// </summary>
        /// <param name="rt_id">Initial value of the Rt_id property.</param>
        /// <param name="acd_id">Initial value of the Acd_id property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="related_Courses">Initial value of the Related_Courses property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        public static Research_Thesis CreateResearch_Thesis(global::System.Int32 rt_id, global::System.Int32 acd_id, global::System.String content, global::System.String related_Courses, global::System.Int32 year, global::System.String subject)
        {
            Research_Thesis research_Thesis = new Research_Thesis();
            research_Thesis.Rt_id = rt_id;
            research_Thesis.Acd_id = acd_id;
            research_Thesis.Content = content;
            research_Thesis.Related_Courses = related_Courses;
            research_Thesis.Year = year;
            research_Thesis.Subject = subject;
            return research_Thesis;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rt_id
        {
            get
            {
                return _Rt_id;
            }
            set
            {
                if (_Rt_id != value)
                {
                    OnRt_idChanging(value);
                    ReportPropertyChanging("Rt_id");
                    _Rt_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Rt_id");
                    OnRt_idChanged();
                }
            }
        }
        private global::System.Int32 _Rt_id;
        partial void OnRt_idChanging(global::System.Int32 value);
        partial void OnRt_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Acd_id
        {
            get
            {
                return _Acd_id;
            }
            set
            {
                OnAcd_idChanging(value);
                ReportPropertyChanging("Acd_id");
                _Acd_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Acd_id");
                OnAcd_idChanged();
            }
        }
        private global::System.Int32 _Acd_id;
        partial void OnAcd_idChanging(global::System.Int32 value);
        partial void OnAcd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Related_Courses
        {
            get
            {
                return _Related_Courses;
            }
            set
            {
                OnRelated_CoursesChanging(value);
                ReportPropertyChanging("Related_Courses");
                _Related_Courses = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Related_Courses");
                OnRelated_CoursesChanged();
            }
        }
        private global::System.String _Related_Courses;
        partial void OnRelated_CoursesChanging(global::System.String value);
        partial void OnRelated_CoursesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BitirmeTeziDatabaseModel", "FK__Research___Acd_i__00200768", "Academic")]
        public Academic Academic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Research___Acd_i__00200768", "Academic").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Research___Acd_i__00200768", "Academic").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Academic> AcademicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Research___Acd_i__00200768", "Academic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Research___Acd_i__00200768", "Academic", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitirmeTeziDatabaseModel", Name="Student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Student : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="std_id">Initial value of the Std_id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="std_no">Initial value of the Std_no property.</param>
        /// <param name="haveThesis">Initial value of the haveThesis property.</param>
        public static Student CreateStudent(global::System.Int32 std_id, global::System.String username, global::System.String name, global::System.String email, global::System.String phone, global::System.String std_no, global::System.Boolean haveThesis)
        {
            Student student = new Student();
            student.Std_id = std_id;
            student.Username = username;
            student.Name = name;
            student.Email = email;
            student.Phone = phone;
            student.Std_no = std_no;
            student.haveThesis = haveThesis;
            return student;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Std_id
        {
            get
            {
                return _Std_id;
            }
            set
            {
                if (_Std_id != value)
                {
                    OnStd_idChanging(value);
                    ReportPropertyChanging("Std_id");
                    _Std_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Std_id");
                    OnStd_idChanged();
                }
            }
        }
        private global::System.Int32 _Std_id;
        partial void OnStd_idChanging(global::System.Int32 value);
        partial void OnStd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Std_no
        {
            get
            {
                return _Std_no;
            }
            set
            {
                OnStd_noChanging(value);
                ReportPropertyChanging("Std_no");
                _Std_no = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Std_no");
                OnStd_noChanged();
            }
        }
        private global::System.String _Std_no;
        partial void OnStd_noChanging(global::System.String value);
        partial void OnStd_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean haveThesis
        {
            get
            {
                return _haveThesis;
            }
            set
            {
                OnhaveThesisChanging(value);
                ReportPropertyChanging("haveThesis");
                _haveThesis = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("haveThesis");
                OnhaveThesisChanged();
            }
        }
        private global::System.Boolean _haveThesis;
        partial void OnhaveThesisChanging(global::System.Boolean value);
        partial void OnhaveThesisChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BitirmeTeziDatabaseModel", "FK__Upload_Th__Std_i__07C12930", "Upload_Thesis")]
        public EntityCollection<Upload_Thesis> Upload_Thesis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Upload_Thesis>("BitirmeTeziDatabaseModel.FK__Upload_Th__Std_i__07C12930", "Upload_Thesis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Upload_Thesis>("BitirmeTeziDatabaseModel.FK__Upload_Th__Std_i__07C12930", "Upload_Thesis", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitirmeTeziDatabaseModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BitirmeTeziDatabaseModel", Name="Upload_Thesis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Upload_Thesis : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Upload_Thesis object.
        /// </summary>
        /// <param name="thesis_id">Initial value of the Thesis_id property.</param>
        /// <param name="std_id">Initial value of the Std_id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="supervisor_id">Initial value of the Supervisor_id property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="approval">Initial value of the Approval property.</param>
        public static Upload_Thesis CreateUpload_Thesis(global::System.Int32 thesis_id, global::System.Int32 std_id, global::System.String title, global::System.String content, global::System.Int32 supervisor_id, global::System.Int32 year, global::System.Boolean approval)
        {
            Upload_Thesis upload_Thesis = new Upload_Thesis();
            upload_Thesis.Thesis_id = thesis_id;
            upload_Thesis.Std_id = std_id;
            upload_Thesis.Title = title;
            upload_Thesis.Content = content;
            upload_Thesis.Supervisor_id = supervisor_id;
            upload_Thesis.Year = year;
            upload_Thesis.Approval = approval;
            return upload_Thesis;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Thesis_id
        {
            get
            {
                return _Thesis_id;
            }
            set
            {
                if (_Thesis_id != value)
                {
                    OnThesis_idChanging(value);
                    ReportPropertyChanging("Thesis_id");
                    _Thesis_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Thesis_id");
                    OnThesis_idChanged();
                }
            }
        }
        private global::System.Int32 _Thesis_id;
        partial void OnThesis_idChanging(global::System.Int32 value);
        partial void OnThesis_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Std_id
        {
            get
            {
                return _Std_id;
            }
            set
            {
                OnStd_idChanging(value);
                ReportPropertyChanging("Std_id");
                _Std_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Std_id");
                OnStd_idChanged();
            }
        }
        private global::System.Int32 _Std_id;
        partial void OnStd_idChanging(global::System.Int32 value);
        partial void OnStd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Document
        {
            get
            {
                return _Document;
            }
            set
            {
                OnDocumentChanging(value);
                ReportPropertyChanging("Document");
                _Document = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Document");
                OnDocumentChanged();
            }
        }
        private global::System.String _Document;
        partial void OnDocumentChanging(global::System.String value);
        partial void OnDocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Supervisor_id
        {
            get
            {
                return _Supervisor_id;
            }
            set
            {
                OnSupervisor_idChanging(value);
                ReportPropertyChanging("Supervisor_id");
                _Supervisor_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Supervisor_id");
                OnSupervisor_idChanged();
            }
        }
        private global::System.Int32 _Supervisor_id;
        partial void OnSupervisor_idChanging(global::System.Int32 value);
        partial void OnSupervisor_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Approval
        {
            get
            {
                return _Approval;
            }
            set
            {
                OnApprovalChanging(value);
                ReportPropertyChanging("Approval");
                _Approval = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Approval");
                OnApprovalChanged();
            }
        }
        private global::System.Boolean _Approval;
        partial void OnApprovalChanging(global::System.Boolean value);
        partial void OnApprovalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BitirmeTeziDatabaseModel", "FK__Upload_Th__Super__08B54D69", "Academic")]
        public Academic Academic
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Upload_Th__Super__08B54D69", "Academic").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Upload_Th__Super__08B54D69", "Academic").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Academic> AcademicReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Upload_Th__Super__08B54D69", "Academic");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Academic>("BitirmeTeziDatabaseModel.FK__Upload_Th__Super__08B54D69", "Academic", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BitirmeTeziDatabaseModel", "FK__Upload_Th__Std_i__07C12930", "Student")]
        public Student Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BitirmeTeziDatabaseModel.FK__Upload_Th__Std_i__07C12930", "Student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BitirmeTeziDatabaseModel.FK__Upload_Th__Std_i__07C12930", "Student").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Student> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Student>("BitirmeTeziDatabaseModel.FK__Upload_Th__Std_i__07C12930", "Student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Student>("BitirmeTeziDatabaseModel.FK__Upload_Th__Std_i__07C12930", "Student", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
